<?php

namespace App\Http\Requests;

use Illuminate\Foundation\Http\FormRequest;

class AdminProductSaveRequest extends FormRequest
{
    /**
     * Determine if the user is authorized to make this request.
     *
     * @return bool
     */
    public function authorize()
    {
        return true;
    }

    /**
     * Get the validation rules that apply to the request.
     *
     * @return array
     */
    public function rules()
    {
        $rule = [
            'title' => 'required|max:90',
            'desc' => 'required',
            'price' => 'required|numeric|min:1,max:9999',
            'code' => 'max:50'
        ];
        if (config('admin.product_qty')) {
            $rule['qty'] = 'required|numeric|min:1';
        }
        return $rule;
    }

    public function messages()
    {
        return parent::messages(); // TODO: Change the autogenerated stub

    }
}
